apiVersion: v1
kind: Pod
metadata:
  name: appzeke-manual-v2
  labels:
    creation_method: manual
    env: prod
    app: demo 
spec:
  containers:
  - image: ashishrpandey/appzeke
    name: appzeke
    ports:
    - containerPort: 8080
      protocol: TCP
